name: Deploy test HashiCorp Terraform Enterprise and sentinel

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

permissions:
  contents: read

env:
#  TF_IN_AUTOMATION: true
  TF_TOKEN_app_terraform_io: ${{ secrets.TFE_TOKEN }}

jobs:
  plan:
    name: terraform plan
    runs-on:
      group: default
    defaults:
      run:
        working-directory: compute-engine
    # container:
    #   image: cr.rak.farnostrakvice.cz:50443/my/my-gcp-terraform:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color -input=false

  apply:
    name: terraform apply
    runs-on:
      group: default
    defaults:
      run:
        working-directory: compute-engine
    # container:
    #   image: cr.rak.farnostrakvice.cz:50443/my/my-gcp-terraform:latest
    needs: plan
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color